version: '3.8'

services:
  mlops-api:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      - APP_DEBUG=false
      - LOG_LEVEL=INFO
      - MODEL_TYPE=logistic
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mlops-dev:
    build:
      context: .
      target: development
    ports:
      - "8001:8000"
    environment:
      - APP_DEBUG=true
      - LOG_LEVEL=DEBUG
      - MODEL_TYPE=logistic
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped
    profiles:
      - dev
